name: Build and Push BAG to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build-and-push.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Rename Original Dockerfile to Dockerfile.old
        run: mv src/Dockerfile src/Dockerfile.old

      - name: Rename Dockerfile_ecs to Dockerfile
        run: mv src/Dockerfile_ecs src/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/bedrock-access-gateway:latest
